language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_script:
  - git fetch --all
  - git reset --hard origin/master

script:
  - ./gradlew build
  - cd ui
  - node -v
  - npm install
  - node_modules/mocha/bin/mocha test
